spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/foodtech_db}
    username: ${SPRING_DATASOURCE_USERNAME:foodtech_user}
    password: ${SPRING_DATASOURCE_PASSWORD:foodtech_pass}
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:create}
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: ${JWT_SECRET:change-me-dev-secret-should-be-32-chars-min}
  expirationSeconds: ${JWT_EXPIRATION_SECONDS:3600}
