spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/foodtech_db
    username: foodtech_user
    password: foodtech_pass
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: "change-me-dev-secret-should-be-32-chars-min"
  expirationSeconds: 3600
